id: I2B249684
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:29:21.194291
last_modified: 2023-01-04 11:29:21.194305
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  '3984':
    title: A Prayer for the Swift Rebirth of Tenpai Nyima Rinpoche
    base_file: 3984.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
